travis:
  secure:
    BINSTAR_TOKEN: iNPJX1ZS+ST1byR71Ht+sMCtbOCpi4A68lorSVxud9X6jRuWNA7DDKk4EAhvj9IXH4nxSUECcOxsgU+iqe+dhydYPm0q9zaDDoCj66OgwjE6w62vxg47UQHHUAsfbOrvmuVnRIJosPJgWqK15NLHX6JYtKqTyN0zn4oipedDvD0BhhxL1raiDbKrRjaMDgDbqFQUJf3MCeo4/xM7Ywg5CnO5x+rF2TsiQfCZX0HoVRkORfyXdT+quh4YtzcBtz+Z7r5m7h/9AmNcroH7HODofh7FOUqWahBPaSGrs1vmlye3WbfYhVlhFvmDBpVOAEJkvgCVKOKoRtSvrNBLmkSRjn60dfkeROEJM7YAPAplyaSMrs8xvtpX2FuXpPIOr3Q2byCB6YrkrjRfpY1KAnHoEdu+TNATtatrqVKXBHZGZSQVWf8do/BIxdMs0sRQ7xSAf+TnSeiW3B9OhW3V8w7QUYvy0dH1EF2/bozBvCoJILvF9jzbo3gFQ3N3Oa4tPl7gener7aK7Sq7BKYDaGw0+UXGhEU/4BXREThjRfMk1Ftblh3yPuDRINAGIRLPw7n6aNQTj15ezbqo6gNfuvnhJUgJqAPK3qiCnJDf5Mro7nc8lNf+WiJGuLZQrdD5Oy6xO/ACCnxKfcLjg8gxEs/6DBZd/BzyZC0hnQunMyU9s06g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
